### ISSUE TITLE
Dons't connect to private zulip server

### ISSUE THREAD

**Issue by wq163** [zulip/zulip-redmine-plugin#1]
I deploy a private zulip server, and zulip-redmine-plugin dons't send message to zulip.
I found hard cord in zulip_hooks.rb :
```
http = Net::HTTP.new("api.zulip.com", 443)
```
and, zulip api path is `api/v1/messages`,but in zulip_hooks.rb :'req = Net::HTTP::Post.new("/v1/messages")'

I hope server and api can specify by users.

**Comment by timabbott** [comment]
Yeah this should be a pretty easy fix for someone who has a redmine setup -- just add an option to control this.  PRs welcome!

**Comment by ogg1e** [comment]
I modified my zulip_hooks.rb to be:

```
        http = Net::HTTP.new("zulip.mycompany.com", 443)
                http.use_ssl = true
        req = Net::HTTP::Post.new("/api/v1/messages")

and reran rake redmine:plugins:migrate RAILS_ENV=production, but that didn't work. It's still throwing a 500 error. Is there more steps involved?

If I could figure out what needs to be done, I could create a PR quickly enough.

**Comment by timabbott** [comment]
A 500 on the Redmine server or the Zulip server?  It'd be great if you had a traceback; one common issue with API apps talking to the Zulip server is that if you're using a self-signed SSL cert or didn't include the full certificate chain in the nginx configuration, you might be getting an SSL validation error...

**Comment by ogg1e** [comment]
500 on the redmine server. I have a valid cert, and it works on the zulip server since I have the jenkins plugin working with it.

**Comment by ogg1e** [comment]
That was the problem. I had to add the certs to apache properly. FYI, I had to do this:
* In /etc/pki/tls/certs/ca-bundle.crt I had to add all the certs I received from the cert provider so each one was appended to the file.
* Edited the /etc/httpd/conf.d/ssl.conf and uncomment this line: SSLCACertificateFile /etc/pki/tls/certs/ca-bundle.crt
* Restart apache

**Comment by ogg1e** [comment]
I created a pull request to allow the url and port to be specified in the admin settings.

https://github.com/zulip/zulip-redmine-plugin/pull/2

**Comment by timabbott** [comment]
Awesome, thanks for debugging this @ogg1e !

**Comment by timabbott** [comment]
PR #2 was merged so this is now fixed!
