### ISSUE TITLE
send message on any issue change not only after save

### ISSUE THREAD

**Issue by hi-ko** [zulip/zulip-redmine-plugin#14]
The plugin only sends message after saving changes in the UI. If an issue is beeing changed by API or inbound email no message is send to zulip.
messages in zulip should behave similar to email notifiations and fired by any change

**Comment by timabbott** [comment]
@felipebatista do you have time to look into this and the other recently opened issue?

**Comment by felipebatista** [comment]
hello guys, I hope you are all fine

[I have been re-coding](https://framagit.org/lobster/redmine_zulip) a **Redmine Zulip** plugin (not technically a fork but based on this one of course) that suits better for my project's workflow. It includes the following features:

* All notifications are triggered on [model callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) (solving **this issue**)
* Include detailed information (solving #13) __*__
* Private message notifications when you get assigned/unassigned to/from an issue, and when **another user** updates a issue you are assigned to. This can be enabled/disabled on project's settings.
* Create a subject for every **issue** _(that has a target version)_, all issue updates are posted on this subject and this is also where project members can discuss about everything concerning the issue. This can be enabled/disabled on project's settings. 
* Create a subject for every **version**, which is a sort of newsfeed for that gets short messages notifications every time an issues is added/removed to/from that version, and also on every **status change** of any issue of that version. This can be enabled/disabled on project's settings.
* Notification messages in English, French, and Brazilian Portuguese (the three languages I can speak, @hi-ko could help me with German translations)

__*__ _This currently only includes the fields we use in our project, I am planning to include very soon all other fields too_

@timabbott would you want to take a look on this code? I can also make a Redmine instance available to you for any kind of test you'd want to peform

**Comment by timabbott** [comment]
@felipebatista sure.  I would be happy to help integrate your rewrite of this plugin into this project; this plugin was originally written years ago and you're the main contributor to it in the last few years.

I don't think I need access to the redmine instance, but I'd love to see the example messages produced by the plugin so I can provide feedback on the formatting you're using. 

(Or probably better @eeshangarg can help with that, as he's been working on making sure all of our integrations use good formatting)

**Comment by felipebatista** [comment]
closed by #15
