### ISSUE TITLE
missing template (redmine 4.0.4)

### ISSUE THREAD

**Issue by danielecr** [zulip/zulip-redmine-plugin#18]
~~~
Missing template, responding with 404: Missing partial projects/settings/_redmine_zulip with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}. Searched in:
  * "/home/redmine/redmine/app/views"

  Rendering common/error.html.erb within layouts/base
  Rendered common/error.html.erb within layouts/base (0.1ms)
Completed 404 Not Found in 257ms (Views: 62.1ms | ActiveRecord: 55.4ms)
Creating scope :system. Overwriting existing method Enumeration.system.
~~~

does not show the settings page of any project

**Comment by timabbott** [comment]
@felipebatista any idea what the issue is here?

**Comment by felipebatista** [comment]
@danielecr thank you for your feedback

I am not experiencing this issue with my Redmine 4.0.4 instance, so let's take a closer look to see what happens.

could you please check f the following file is present in your installation directory?

![redmine-zulip-plugin-view](https://user-images.githubusercontent.com/213949/64016226-ab9e8800-cb26-11e9-8aeb-bc8e60e97c1d.jpg)

**Comment by danielecr** [comment]
~~~
ls redmine_zulip/app/views/projects/settings/
_redmine_zulip.html.erb
~~~
yes, it is there

**Comment by danielecr** [comment]
~~~
Migrating plugins. Please be patient, this could take a while...
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddZulipAuthToProject < ActiveRecord::Migration[4.2]
~~~
I have this message on starting redmine. Then it crashs

**Comment by felipebatista** [comment]
@danielecr thank you for the additional info, that made me detect the source of the problem

could you please try with the new **3.0** release and gimme a feedback?

**Comment by danielecr** [comment]
@felipebatista yes, thank you so much, it works!

**Comment by danielecr** [comment]
... oh, well, I just tried to use it, I have internal server error (500) updating an issue in redmine:
(I omitted to post data, mostly)
~~~
Processing by IssuesController#update as HTML
  Parameters: {...OMITTED... "last_journal_id"=>"", "commit"=>"Submit", "next_issue_id"=>"894", "issue_position"=>"1", "issue_count"=>"22", "id"=>"895"}
  Current user: danielecr (id=5)
Completed 500 Internal Server Error in 161ms (ActiveRecord: 33.4ms)
  
NoMethodError (undefined method `request_uri' for #<URI::Generic zulip.starsellersworld.com/api/v1/messages>):
~~~

I setted the project to notify to the bot on all event (all checked), I specified the channel name using '+' for the space, this way "react+team"

**Comment by felipebatista** [comment]
@danielecr I think you just need to specify the protocol (http / https) on your Zulip URL settings

![zulip-redmine-settings-url](https://user-images.githubusercontent.com/213949/64104182-0e389380-cd74-11e9-80cc-58e524ace8c0.jpg)

**Comment by danielecr** [comment]
yes, sorry. So it works
