### ISSUE TITLE
global settings

### ISSUE THREAD

**Issue by hi-ko** [zulip/zulip-redmine-plugin#19]
in version 1.0 one could use global notification config which could be overwritten by project config.
In version>= 2.0 we have to explicitly set zulip notification settings in every project.

It would help a lot if either configuration could be set by global default and/or to inherit from parent projects.

**Comment by hi-ko** [comment]
as a work around one could set default behavior on the database. e.g. (using an existing zulip_stream):
````
UPDATE projects
SET zulip_private_messages=1,
    zulip_subject_issue=1,
    zulip_subject_version=1,
    zulip_stream="announce"
    
WHERE 
    zulip_stream="";
````

**Comment by felipebatista** [comment]
hello @hi-ko, could you try the new unreleased versions **2.1-alpha1** or **3.1-alpha1**

* 2.x versions of this plugin are compatible with Redmine **3.x**
* 3.x versions of this plugin are compatible with Redmine **4.x**

thank you!

**Comment by hi-ko** [comment]
perfect!

- I could set default values in plugin config / admin 
- and I can set specific values in the project's zulip config

thank you!
