### ISSUE TITLE
Redmine 3.4 doesn't  work

### ISSUE THREAD

**Issue by inakhai** [zulip/zulip-redmine-plugin#20]
Redmine 3.4 doesn't  select menu in Projects-->Settings

```
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back
```
can you help me how to fix

Tom

**Comment by felipebatista** [comment]
@inakhai thank you for the feedback

please try the vesion **2.0.2**

versions **3.x** of this plugin are only compatible with Redmine 4.x

let me know if you still have problems with version **2.0.2** and Redmine **3.4**

**Comment by inakhai** [comment]
@felipebatista thanks you so much It working property
