### ISSUE TITLE
supress email notification by config

### ISSUE THREAD

**Issue by hi-ko** [zulip/zulip-redmine-plugin#27]
Redmine does not support detailed configuration for email notifications (which projects emails should be send) but to avoid redundant notifications by email and zulip it would be a very nice feature to support suppressing emails by config (global/per project).
How to implement this could be seen in the plugin [redmine_silencer/issue_hooks.rb](https://github.com/paginagmbh/redmine_silencer/blob/master/lib/redmine_silencer/issue_hooks.rb) which is focusing on the role - not on the project.

**Comment by batistadasilva** [comment]
hello @hi-ko, 

I am not sure that this plugin is the right component to implement this feature. In my opinion, suppressing email notifications is beyond Zulip integration scope.

I see two better solutions for your issue:

* Submitting a new feature request on **Redmine Silencer** project asking for global/per project email notifications suppressing
* Let users disable email notifications on their own account settings if they find it redundant

thanks again

**Comment by hi-ko** [comment]
Hi @felipebatista,
feel free to close the issue as out of scope but since redmine does not provide that option it would be an easy implementation without the need to have additional dependencies / plugins like Redmine Silencer.
Maybe I'll try to adopt the hook in a fork not to depend on another plugin.

Thanks
