### ISSUE TITLE
How to debug this integration?

### ISSUE THREAD

**Issue by leoniscsem** [zulip/zulip-redmine-plugin#3]
I have tried to implement the integration as documented and our Redmine instances posts the tickets as far as the logs tell me. Yet in Zulip nothing shows up so I am wondering which log to check or how to verify the bot is active?

**Comment by timabbott** [comment]
If the requests from the Redmine integration are reaching the Zulip server, then /var/log/zulip/server.log should show the requests; it can be faster to skim for errors in /var/log/zulip/errors.log.

**Comment by timabbott** [comment]
This question was answered, closing.
